services:
    db:
      image: postgis/postgis
      restart: always
      environment:
        POSTGRES_DB: ecommerce
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data1
      ports:
        - "5432:5432"
   
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
     
volumes:
  pgdata:  
  
